version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antfu
  - Attributify
  - Ayabit
  - changelogen
  - CODEMAP
  - composables
  - defu
  - Guii
  - guiiai
  - iconify
  - lucide
  - memfs
  - mkdist
  - nodir
  - nuxi
  - Nuxt
  - openai
  - pinia
  - unocss
  - unplugin
  - vite
  - vitepress
  - vnode
  - nprogress
  - vueuse
  - unref
  - dustella
  - lastmod
  - juejin
  - opengraph
ignoreWords: []
import: []
