version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antfu
  - arctan
  - Attributify
  - Ayabit
  - changelogen
  - CODEMAP
  - composables
  - defu
  - dustella
  - FPFH
  - giscus
  - Guii
  - guiiai
  - iconify
  - juejin
  - Kanade
  - lastmod
  - lucide
  - mathcal
  - memfs
  - mkdist
  - nodir
  - nprogress
  - nuxi
  - Nuxt
  - openai
  - opengraph
  - pinia
  - RANSAC
  - stylelint
  - unocss
  - unplugin
  - unref
  - vite
  - vitepress
  - vnode
  - vueuse
ignoreWords: []
import: []
